### ISSUE TITLE
Issues with TapAndPay SDK Integration in React Native Project

### ISSUE THREAD

**Issue by JuanValeraDev** [swan-io/swan-partner-mobile#19]
Hello, I'm trying to run this Swan project integrated with React Native but I've encountered a problem related to the TapAndPay SDK. I can't get it and without it, it doesn't work for me. Here are the steps I've followed in my attempt:

- I clone the github repository with "git clone https://github.com/swan-io/swan-partner-mobile.git"
- I install the dependencies with the "yarn" command in root and in /server. I don't run "pod install" in ios/ because I'm not going to use ios, only android.
- I skip the Google Pay part because I can't get an authorized google account and therefore I can't download the TapAndPay SDK: 
<img width="880" alt="Screenshot 2024-05-08 at 17 50 56" src="https://github.com/swan-io/swan-partner-mobile/assets/85889717/81c08172-829e-4b16-b863-468f566e3258">

- I copy the content of .env.example into .env changing "PARTNER_API_URL="https://api.swan.io/live-partner/graphql"" to "PARTNER_API_URL="https://api.swan.io/sandbox-partner/graphql" because I'm using sandbox.
- I also copy the content of server/.env.example into server/.env modifying the values of OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET and SESSION_TOKEN_PASSWORD to be the ones that appear in my Swan Dashboard and "PARTNER_API_URL="https://api.swan.io/live-partner/graphql"
  " to "PARTNER_API_URL="https://api.swan.io/sandbox-partner/graphql"  
  "  
- I add my AUTH_REDIRECT_URI, which is "http://localhost:8103/auth/callback" to my Dashboard -> Redirect URIS.
- I run an android emulator.
- Then I run "yarn dev" in server/
<img width="529" alt="Screenshot 2024-05-08 at 18 20 58" src="https://github.com/swan-io/swan-partner-mobile/assets/85889717/d57c7f50-ae03-4475-9ce0-c99bb1fa02a1">

- And then "yarn android" in the root.
- Once Metro has started, I press "a" to run the "run on Android" option
- When the application is compiling, errors related to the TapAndPay SDK jump out. Here are some examples:

<img width="769" alt="Screenshot 2024-05-08 at 18 35 04" src="https://github.com/swan-io/swan-partner-mobile/assets/85889717/bedfa979-9b92-4393-a5fd-501f206b383e">
<img width="774" alt="Screenshot 2024-05-08 at 18 29 22" src="https://github.com/swan-io/swan-partner-mobile/assets/85889717/27b83836-4450-47a4-87cc-3fdd52a2019a">

- Therefore, I have a doubt: Is it mandatory to include the TapAndPay SDK for the application to work? Isn't there an alternative so that it isn't? And in case it is totally mandatory, Can a regular user get an authorized Google account for free?

Thank you very much for the help.

**Comment by zoontek** [comment]
Hi @JuanValeraDev!

These errors are normal if you don't unzip the SDK. You absolutely need it to work with Google Wallet. Why can't you get an authorized google account? You will need one to publish an app with such a feature.
